# PoSh-Backup Remote Version Manifest
# Generated: Saturday 31 May 2025, 14:48:19
#
# This file provides information about the latest official release of PoSh-Backup.
# It is fetched by the -CheckForUpdate feature.
#
@{
    LatestVersion   = '1.39.0'
    ReleaseDate     = '2025-06-02'
    ReleaseNotesUrl = 'https://github.com/BootBlock/PoSh-Backup/releases/tag/v1.14.6'
    DownloadUrl     = 'https://github.com/BootBlock/PoSh-Backup/archive/refs/tags/v1.14.6.zip'
    SHA256Checksum  = '1725B9757220A59F94E13A444DBF201751362B01E0525F1F36C4FB68A40AC330'
    Severity        = 'Recommended'
    Message         = ''
    ScriptVersions  = @{
        'Meta\\apply_update.ps1' = '1.0.0'
        'Meta\\BundlerModules\\Bundle.ExternalTools.psm1' = '1.1.0'
        'Meta\\BundlerModules\\Bundle.FileProcessor.psm1' = '1.0.1'
        'Meta\\BundlerModules\\Bundle.ProjectScanner.psm1' = '1.0.2'
        'Meta\\BundlerModules\\Bundle.StateAndAssembly.psm1' = '1.1.16'
        'Meta\\BundlerModules\\Bundle.Utils.psm1' = '1.0.0'
        'Meta\\Generate-ProjectBundleForAI.ps1' = '1.25.2'
        'Modules\\ConfigManagement\\ConfigLoader.psm1' = '1.3.0'
        'Modules\\ConfigManagement\\ConfigLoader\\AdvancedSchemaValidatorInvoker.psm1' = '1.0.0'
        'Modules\\ConfigManagement\\ConfigLoader\\BasicValidator.psm1' = '1.0.0'
        'Modules\\ConfigManagement\\ConfigLoader\\MergeUtil.psm1' = '1.0.0'
        'Modules\\ConfigManagement\\ConfigLoader\\SevenZipPathResolver.psm1' = '1.0.0'
        'Modules\\ConfigManagement\\ConfigLoader\\UserConfigHandler.psm1' = '1.0.0'
        'Modules\\ConfigManagement\\EffectiveConfigBuilder.psm1' = '1.1.0'
        'Modules\\ConfigManagement\\EffectiveConfigBuilder\\ArchiveSettings.psm1' = '1.0.0'
        'Modules\\ConfigManagement\\EffectiveConfigBuilder\\DestinationSettings.psm1' = '1.0.0'
        'Modules\\ConfigManagement\\EffectiveConfigBuilder\\OperationalSettings.psm1' = '1.0.0'
        'Modules\\ConfigManagement\\EffectiveConfigBuilder\\SevenZipSettings.psm1' = '1.0.0'
        'Modules\\ConfigManagement\\JobResolver.psm1' = '1.0.1'
        'Modules\\Core\\ConfigManager.psm1' = '1.2.1'
        'Modules\\Core\\JobOrchestrator.psm1' = '1.1.4'
        'Modules\\Core\\Operations.psm1' = '1.22.0'
        'Modules\\Core\\Operations\\JobExecutor.FinalisationHandler.psm1' = '1.0.0'
        'Modules\\Core\\Operations\\JobExecutor.LocalBackupOrchestrator.psm1' = '1.0.0'
        'Modules\\Core\\Operations\\JobExecutor.LocalRetentionHandler.psm1' = '1.0.0'
        'Modules\\Core\\Operations\\JobExecutor.PostJobHookHandler.psm1' = '1.0.1'
        'Modules\\Core\\Operations\\JobExecutor.psm1' = '1.6.1'
        'Modules\\Core\\Operations\\JobExecutor.RemoteTransferHandler.psm1' = '1.0.0'
        'Modules\\Core\\Operations\\JobExecutor.VssCleanupHandler.psm1' = '1.0.0'
        'Modules\\Core\\PostRunActionOrchestrator.psm1' = '1.0.1'
        'Modules\\Managers\\7ZipManager.psm1' = '1.2.1'
        'Modules\\Managers\\7ZipManager\\ArgumentBuilder.psm1' = '1.0.0'
        'Modules\\Managers\\7ZipManager\\Discovery.psm1' = '1.0.0'
        'Modules\\Managers\\7ZipManager\\Executor.psm1' = '1.0.0'
        'Modules\\Managers\\HookManager.psm1' = '1.0.1'
        'Modules\\Managers\\JobDependencyManager.psm1' = '0.3.4'
        'Modules\\Managers\\LogManager.psm1' = '1.1.0'
        'Modules\\Managers\\PasswordManager.psm1' = '1.2.3'
        'Modules\\Managers\\RetentionManager.psm1' = '1.2.4'
        'Modules\\Managers\\RetentionManager\\Deleter.psm1' = '1.0.3'
        'Modules\\Managers\\RetentionManager\\Scanner.psm1' = '1.0.0'
        'Modules\\Managers\\SystemStateManager.psm1' = '1.0.2'
        'Modules\\Managers\\VssManager.psm1' = '1.0.3'
        'Modules\\Operations\\JobPreProcessor.psm1' = '1.0.3'
        'Modules\\Operations\\LocalArchiveProcessor.psm1' = '1.0.14'
        'Modules\\Operations\\RemoteTransferOrchestrator.psm1' = '1.0.1'
        'Modules\\PoShBackupValidator.psm1' = '1.7.0'
        'Modules\\PoShBackupValidator\\SchemaExecutionEngine.psm1' = '1.0.0'
        'Modules\\Reporting.psm1' = '2.3.3'
        'Modules\\Reporting\\ReportingCsv.psm1' = '1.2.3'
        'Modules\\Reporting\\ReportingHtml.psm1' = '1.9.11'
        'Modules\\Reporting\\ReportingJson.psm1' = '1.1.4'
        'Modules\\Reporting\\ReportingMd.psm1' = '1.3.2'
        'Modules\\Reporting\\ReportingTxt.psm1' = '1.2.3'
        'Modules\\Reporting\\ReportingXml.psm1' = '1.2.2'
        'Modules\\ScriptModeHandler.psm1' = '1.1.0'
        'Modules\\Targets\\Replicate.Target.psm1' = '1.0.2'
        'Modules\\Targets\\SFTP.Target.psm1' = '1.0.6'
        'Modules\\Targets\\UNC.Target.psm1' = '1.1.3'
        'Modules\\Utilities\\ConfigUtils.psm1' = '1.0.0'
        'Modules\\Utilities\\ConsoleDisplayUtils.psm1' = '1.1.3'
        'Modules\\Utilities\\FileUtils.psm1' = '1.0.0'
        'Modules\\Utilities\\StringUtils.psm1' = '1.0.0'
        'Modules\\Utilities\\SystemUtils.psm1' = '1.0.0'
        'Modules\\Utilities\\Update.psm1' = '0.2.0'
        'Modules\\Utils.psm1' = '1.16.0'
        'PoSh-Backup.ps1' = '1.14.6'
        'Tests\\Modules\\Utilities\\ConfigUtils.Tests.ps1' = 'N/A'
        'Tests\\Modules\\Utilities\\FileUtils.Tests.ps1' = 'N/A'
    }
}
